# Generated by Django 2.0.1 on 2020-05-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20200518_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': {('permissao3', 'Permissao 3'), ('permisao2', 'Permissao 2'), ('setar_nfe', 'Usuario pode alterar parametro NFe')}},
        ),
    ]
