# Generated by Django 2.0.1 on 2020-05-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20200519_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': {('ver_dashboard', 'Pode visualizar dashboard'), ('setar_nfe', 'Usuario pode alterar parametro NFe'), ('permissao3', 'Permissao 3')}},
        ),
    ]
