# Generated by Django 2.0.1 on 2020-05-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': {('list_person', 'Listar clientes')}},
        ),
    ]
